[[introduction]]
== Overview
:xrefstyle: short

The primary focus of this <<dmh,DMH>> is on the management of <<glossary-dynamic-geodata, dynamic geodata>>. <<glossary-dynamic-geodata, Dynamic geodata>> is weather, environment and climate-related data that changes in space and time and is thus descriptive of processes in nature. Examples are weather observations, weather forecasts, pollution (environmental toxins) in water, air and sea, water flow in rivers, driving conditions on the roads. <<glossary-dynamic-geodata, Dynamic geodata>> provides important constraints for many decision-making processes and activities in society.


The intended audience for this DMH is any personell involved in the process of making data available for the end user. This process can be viewed as a value chain that moves from the producer of the data to the data consumer (i.e., the end user). 

The purpose of the Data Management Handbook (<<dmh,DMH>>) is threefold:

1. to provide an overview of the principles for data management to be employed;
2. to help personnel identify their roles and responsibilities for good data management; and
3. to provide personnel with practical guidelines for carrying out good data management.

<<glossary-data-management,_Data management_>> is the term used to describe the handling of data in a systematic and cost-effective manner. The data management regime should be continuously evolving, to reflect the evolving nature of data collection. Therefore this <<dmh,DMH>> is a living document that will be revised and updated from time to time in order to maintain its relevance.

The <<dmh,DMH>> is a strategic governing document and should be used as part of the quality framework the organisation is using. 
