[[summary]]
== Summary
:xrefstyle: short
[[PrinciplesDataManagement]]
=== The principles of data management for dynamic geodata

Principles of standardised data documentation, publication, sharing and preservation have been formalised in the <<glossary-fair-principles,FAIR>> Guiding Principles for scientific data management and stewardship [https://www.nature.com/articles/sdata201618[RD3]] through a process facilitated by <<force11,FORCE11>>. FAIR stands for findability, accessibility, <<glossary-interoperability,interoperability>> and reusability.

By following the <<fair,FAIR>> principles it is easier to obtain a common approach to <<glossary-data-management,data management>>, or a <<glossary-unified-data-management, unified data management>> model. One of the main motivations for implementing a <<glossary-unified-data-management, unified data management>> is to better serve the users of the data. Primarily, this can be approached by making user needs and requirements the guide for determining what data we provide and how. For example, it will be described below how the specification of <<glossary-dataset,datasets>> should be determined. By implementing the data management practices described here, it is expected that users will experience:

* Ease of discovering, viewing and accessing <<glossary-dataset,datasets>>;
* Standardised ways of accessing data, including downloading or streaming data, with reduced need for special solutions on the user side;
* Reduced storage needs;
* Simple and standard access to remote <<glossary-dataset,datasets>> and catalogues, with own data visualisation and analysis tools;
* Ability to compare and combine data from internal and external sources;
* Ability to apply common data transformations, like spatial, temporal and variables subsetting and reprojection, before downloading anything;
* Possibility to build specialized metadata catalogues and data portals targeting a specific user community.

[[dataset]]
==== Dataset

A <<glossary-dataset,dataset>> is a collection of data. In the context of the <<glossary-data-management,data management>> model, the storage mode of the <<glossary-dataset,dataset>> is irrelevant, since access mechanisms can be decoupled from the storage layer as experienced by a data consumer. Typically, a <<glossary-dataset,dataset>> represents a number of variables in time and space. A more detailed definition is provided in the <<glossary-glossary,Glossary of Terms>>. In order to best serve the data through <<web-service,web services>>, the following principles are useful for guiding the <<glossary-dataset,dataset>> definition:

1. A <<glossary-dataset,dataset>> can be a collection of variables stored in, for example, a relational database or as flat files;
2. A <<glossary-dataset,dataset>> is defined as a number of spatial and/or temporal variables;
3. A <<glossary-dataset,dataset>> should be defined by the information content and not the production method;
4. A good <<glossary-dataset,dataset>> does not mix <<glossary-feature-type,feature types>>, i.e., trajectories and gridded data should not be present in the same <<glossary-dataset,dataset>>.

Point 3 implies that the output of, e.g., a numerical model may be divided into several <<glossary-dataset,datasets>> that are related. This is also important in order to efficiently serve the data through <<glossary-webservice,web services>>. For instance, model variables defined on different vertical coordinates should be separated as <<glossary-linked-data,linked datasets>>, since some <<ogc,OGC>> services (e.g., <<wms,WMS>>) are unable to handle mixed coordinates in the same <<glossary-dataset,dataset>>. One important linked dataset relation is the parent-child relationship. In the numerical model example, the parent dataset would be the model simulation. This (parent) dataset encompasses all datasets created by the model simulation such as, e.g., two NetCDF-CF files (child datasets) with different information content.

Most importantly, a <<glossary-dataset,dataset>> should be defined to meet the consumer needs. This means that the specification of a <<glossary-dataset,dataset>> should follow not only the content guidelines just listed, but also address the consumer needs for data delivery, security and preservation.

//Metadata needs to be in summary, but maybe not all metadata information? 
[[metadata]]
==== Metadata

Metadata is a broad concept. In our <<glossary-data-management,data management>> model the term "metadata" is used in several contexts, specifically the five categories that are briefly described in <<table-metadata>>. 

.Brief introduction to different types of metadata.
[[table-metadata]]
[%header, cols=4*]
|===
|Type
|Purpose
|Description
|Examples

|[[discovery-metadata]]Discovery metadata
|Used to find relevant data
|Discovery metadata are also called index metadata and are a digital version of the library index card. They describe who did what, where and when, how to access data and potential constraints on the data. They shall also link to further information on the data, such as <<site-metadata,site metadata>>.
|<<ISO-19115,ISO 19115>> +
<<gcmd,GCMD>>/<<dif,DIF>>

|[[use-metadata]]Use metadata
|Used to understand data found
|Use metadata describes the actual content of a <<glossary-dataset,dataset>> and how it is encoded. The purpose is to enable the user to understand the data without any further communication. They describe the content of variables using standardised vocabularies, units of variables, encoding of missing values, map projections, etc.
|<<cf,Climate and Forecast (CF) Convention>> +
<<bufr,BUFR>> +
<<grib,GRIB>>

|[[site-metadata]]Site metadata
|Used to understand data found
|Site metadata are used to describe the context of observational data. They describe the location of an observation, the instrumentation, procedures, etc. To a certain extent they overlap with <<discovery-metadata,discovery metadata>>, but also extend discovery metadata. Site metadata can be used for observation network design. Site metadata can be considered a type of <<use-metadata,use metadata>>.
|<<wigos,WIGOS>> +
<<ogc-om,OGC O&M>>

|[[configuration-metadata]]Configuration metadata
|Used to tune portal services for <<glossary-dataset,datasets>> intended for data consumers (e.g., WMS)
|Configuration metadata are used to improve the services offered through a portal to the user community. This can, e.g., be how to best visualise a <<glossary-product,product>>.
|

|[[system-metadata]]System metadata
|Used to understand the technical structure of the <<glossary-data-management,data management>> system and track changes in it 
|System metadata covers, e.g., technical details of the storage system, <<glossary-web-service,web services>>, their purpose and how they interact with other components of the <<glossary-data-management,data management>> system, available and consumed storage, number of users and other KPI elements etc.
|
|===

The tools and facilities used to manage the information for efficient discovery and use are further described in <<structuring-and-documenting>>.

:numbered:
include::{special_intro}[]
