= Data Management Handbook template for S-ENDA
Nina E. Larsgård, Bruce Hackett, Audun Christoffersen, Øystein Godøy, Vegar Kristiansen, Martin Grønlien Pejcoch, Eivind Støylen, Elodie Fernandez, Morten W. Hansen, Trygve Aspenes, Arnulf Heimsbakk (MET), Matteo De Stefano (NINA), Lise Eder Murberg (NILU), Viviane Girardin (NIVA) and Ivana Huskova (NIVA)


== Introduction 

This document describes general data management practices in line with the FAIR (Findable, Accessible, Interoperable and Reusable) guiding principles for scientific data management, and focuses on the management and sharing of dynamical geodata (i.e., geolocated data about processes in nature). The practices aim at a metadata-driven data management regime. The present handbook is a general text (under development) that can be applied by anyone. We have prepared templates for organisation specific information that can be updated and merged into the general handbook by the user organisations.

The purpose of the Data Management Handbook (<<dmh,DMH>>) is threefold:

1. to provide an overview of the principles for FAIR data management to be employed;
2. to help personnel identify their roles and responsibilities for good data management; and
3. to provide personnel with practical guidelines for carrying out good data management.

<<glossary-data-management,_Data management_>> is the term used to describe the handling of data in a systematic and cost-effective manner. The data management regime should be continuously evolving, to reflect the evolving nature of data collection. Therefore this <<dmh,DMH>> is a living document that will be revised and updated from time to time in order to maintain its relevance.

The primary focus of this <<dmh,DMH>> is on the management of <<glossary-dynamic-geodata, dynamic geodata>>. <<glossary-dynamic-geodata, Dynamic geodata>> is weather, environment and climate-related data that changes in space and time and is thus descriptive of processes in nature. Examples are weather observations, weather forecasts, pollution (environmental toxins) in water, air and sea, water flow in rivers, driving conditions on the roads. <<glossary-dynamic-geodata, Dynamic geodata>> provides important constraints for many decision-making processes and activities in society.

The document has 4 main pillars: overview, practical guide, insight and references. The overview gives a summery of the most important data management principles. In the practical guide data producers are provided with practical guidance to FAIR data management at their respective institution. Further details and a deeper understanding of FAIR data management principles is provided in insight. 

// 'FAIR' should be in the glossary. 
