= Data Management Handbook template for MET and partners in S-ENDA
Nina E. Larsgård, Bruce Hackett, Audun Christoffersen, Øystein Godøy, Vegar Kristiansen, Martin Grønlien Pejcoch, Eivind Støylen, Elodie Fernandez, Morten W. Hansen, Trygve Aspenes, Arnulf Heimsbakk (MET), Matteo De Stefano (NINA), Lise Eder Murberg (NILU), Viviane Girardin (NIVA) and Ivana Huskova (NIVA)


== Introduction / Abstract

This document describes general data management practices in line with the FAIR guiding principles for scientific data management, and focuses on the management and sharing of dynamical geodata (i.e., geolocated data about processes in nature). The practices aim at a metadata-driven data management regime. The document is devided into 4 pillars: overview, practical guide, insights and references. The overview gives a summary of the most important data management principles. In the practical guide data producers are provided with practical guidance to FAIR data management at their respective institution. Insights provide the reader with details of implementing FAIR principles and are described along 4 pillars: structuring and documenting data; data services; user portals and documentation; and data governance. 

The present handbook is a general text (under development) that can be applied by anyone. We have prepared templates for organisation specific information that can be updated and merged into the general handbook by the user organisations.


